Web/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: "pages#index"
  #get 'pages/index'

  resources :pictures
  resources :conventions
  resources :reports
  resources :points
  resources :visitors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Web/app/models/visitor.rb
class Visitor < ApplicationRecord
end

Web/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:mail, :name, :phone, :address)
    end
end

Web/app/helpers/visitors_helper.rb
module VisitorsHelper
end

Web/app/views/visitors/_form.html.erb
<%= form_for(visitor) do |f| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mail %>
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web/app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

Web/app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitors</h1>

<table>
  <thead>
    <tr>
      <th>Mail</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.mail %></td>
        <td><%= visitor.name %></td>
        <td><%= visitor.phone %></td>
        <td><%= visitor.address %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

Web/app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

Web/app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mail:</strong>
  <%= @visitor.mail %>
</p>

<p>
  <strong>Name:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @visitor.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @visitor.address %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>