Web/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: "pages#index"
  #get 'pages/index'

  resources :pictures
  resources :conventions
  resources :reports
  resources :points
  resources :visitors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Web/app/models/convention.rb
class Convention < ApplicationRecord
end

Web/app/controllers/conventions_controller.rb
class ConventionsController < ApplicationController
  before_action :set_convention, only: [:show, :edit, :update, :destroy]

  # GET /conventions
  # GET /conventions.json
  def index
    @conventions = Convention.all
  end

  # GET /conventions/1
  # GET /conventions/1.json
  def show
  end

  # GET /conventions/new
  def new
    @convention = Convention.new
  end

  # GET /conventions/1/edit
  def edit
  end

  # POST /conventions
  # POST /conventions.json
  def create
    @convention = Convention.new(convention_params)

    respond_to do |format|
      if @convention.save
        format.html { redirect_to @convention, notice: 'Convention was successfully created.' }
        format.json { render :show, status: :created, location: @convention }
      else
        format.html { render :new }
        format.json { render json: @convention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conventions/1
  # PATCH/PUT /conventions/1.json
  def update
    respond_to do |format|
      if @convention.update(convention_params)
        format.html { redirect_to @convention, notice: 'Convention was successfully updated.' }
        format.json { render :show, status: :ok, location: @convention }
      else
        format.html { render :edit }
        format.json { render json: @convention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conventions/1
  # DELETE /conventions/1.json
  def destroy
    @convention.destroy
    respond_to do |format|
      format.html { redirect_to conventions_url, notice: 'Convention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convention
      @convention = Convention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def convention_params
      params.require(:convention).permit(:convention, :description, :image)
    end
end

Web/app/helpers/conventions_helper.rb
module ConventionsHelper
end

Web/app/views/conventions/_form.html.erb
<%= form_for(convention) do |f| %>
  <% if convention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convention.errors.count, "error") %> prohibited this convention from being saved:</h2>

      <ul>
      <% convention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :convention %>
    <%= f.text_field :convention %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web/app/views/conventions/edit.html.erb
<h1>Editing Convention</h1>

<%= render 'form', convention: @convention %>

<%= link_to 'Show', @convention %> |
<%= link_to 'Back', conventions_path %>

Web/app/views/conventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conventions</h1>

<table>
  <thead>
    <tr>
      <th>Convention</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conventions.each do |convention| %>
      <tr>
        <td><%= convention.convention %></td>
        <td><%= convention.description %></td>
        <td><%= convention.image %></td>
        <td><%= link_to 'Show', convention %></td>
        <td><%= link_to 'Edit', edit_convention_path(convention) %></td>
        <td><%= link_to 'Destroy', convention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Convention', new_convention_path %>

Web/app/views/conventions/new.html.erb
<h1>New Convention</h1>

<%= render 'form', convention: @convention %>

<%= link_to 'Back', conventions_path %>

Web/app/views/conventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Convention:</strong>
  <%= @convention.convention %>
</p>

<p>
  <strong>Description:</strong>
  <%= @convention.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @convention.image %>
</p>

<%= link_to 'Edit', edit_convention_path(@convention) %> |
<%= link_to 'Back', conventions_path %>